locations_name = [
    "Hive Primus",
    "Ebonspire",
    "Necropolis Prime",
    "Adamantine Reach",
    "Hive Stygia",
    "Obsidian Bastion",
    "Ironheart Enclave",
    "Hive Argentum",
    "Verminopolis",
    "Ashen Citadel",
    "Hive Gehenna",
    "Penumbral Hive",
    "Hive Scoria",
    "Ossuary Heights",
    "Hive Crucible"
]


ultramarine_names = [
    "Marneus Calgar",
    "Cato Sicarius",
    "Uriel Ventris",
    "Aeonid Thiel",
    "Agemman",
    "Tigurius",
    "Aethon",
    "Avitus",
    "Tiberius",
    "Galenus",
    "Octavian",
    "Severus",
    "Cassian",
    "Valerian",
    "Corvin",
    "Decimus",
    "Lucian",
    "Lucius",
    "Maximus",
    "Gaius",
    "Marius",
    "Titus",
    "Felix",
    "Lucullus",
    "Decius",
    "Pertinax",
    "Valentinian",
    "Gaius Julius",
    "Theodoric",
    "Aurelius",
    "Quintus",
    "Rufus",
    "Castor",
    "Cincinnatus",
    "Didius",
    "Fabian",
    "Gracchus",
    "Hadrian",
    "Horatius",
    "Julius",
    "Justinian",
    "Marcellus",
    "Marcus",
    "Nero",
    "Ovidius",
    "Publius",
    "Remus",
    "Scipio",
    "Seneca",
    "Sulla",
    "Tacticus",
    "Valerius",
    "Vespasian",
    "Virgil",
    "Xerxes",
    "Zephyrus",
    "Aelian",
    "Alaric",
    "Antares",
    "Aquilon",
    "Archimedes",
    "Arcturus",
    "Ares",
    "Argus",
    "Asmodeus",
    "Aurum",
    "Bellerophon",
    "Calibos",
    "Castellan",
    "Centurion",
    "Chromius",
    "Corvus",
    "Crassus",
    "Decimus Maximus",
    "Dominus",
    "Draco",
    "Drusus",
    "Eleutherios",
    "Emilian",
    "Equinox",
    "Fabius",
    "Falkus",
    "Ferox",
    "Gallus",
    "Garro",
    "Gideon",
    "Gorgon",
    "Gravitas",
    "Hector",
    "Helios",
    "Ignatius",
    "Inquisitorius",
    "Janus",
    "Javelin",
    "Jupiter",
    "Justus",
    "Kestros",
    "Korax",
    "Leonidas",
    "Libertas",
    "Lysander",
    "Magnus",
    "Marcellian",
    "Maximilian",
    "Mortifer",
    "Nemesis",
    "Nemean",
    "Nocturnus",
    "Octavianus",
    "Orpheus",
    "Paladin",
    "Patricius",
    "Pentheus",
    "Phoebus",
    "Placidus",
    "Prometheus",
    "Proteus",
    "Pyrrhus",
    "Quirinus",
    "Radamanthys",
    "Ragnar",
    "Remulus",
    "Romulus",
    "Sanguinius",
    "Scarius",
    "Scipionis",
    "Septimus",
    "Seraphim",
    "Silvanus"]

